
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND CLOSE CL_COMMENT IF IFF NOT NUMERAL OPEN OR QUOTEDSTRING RESERVEDELEMENT\n\t\tstarter : sentence\n\t\t\t\t| sentence starter\n\t\t\n\t\tsentence : OPEN AND QUOTEDSTRING QUOTEDSTRING CLOSE\n\t\t'
    
_lr_action_items = {'OPEN':([0,2,8,],[3,3,-3,]),'$end':([1,2,4,8,],[0,-1,-2,-3,]),'AND':([3,],[5,]),'QUOTEDSTRING':([5,6,],[6,7,]),'CLOSE':([7,],[8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'starter':([0,2,],[1,4,]),'sentence':([0,2,],[2,2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> starter","S'",1,None,None,None),
  ('starter -> sentence','starter',1,'p_starter','silver_chainsaw.py',95),
  ('starter -> sentence starter','starter',2,'p_starter','silver_chainsaw.py',96),
  ('sentence -> OPEN AND QUOTEDSTRING QUOTEDSTRING CLOSE','sentence',5,'p_sentence','silver_chainsaw.py',103),
]
