
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND CLOSE CL_COMMENT IF IFF NOT NUMERAL OPEN OR QUOTEDSTRING RESERVEDELEMENT\n\t\tstarter : sentence \n\t\t\t\t| sentence starter\n\t\t\n\t\tinterpretedname : NUMERAL \n\t\t\t\t| QUOTEDSTRING\n\t\t\n\t\tsentence : atomsent\n\t\t\t\t| boolsent\n\t\t\n\t\tpredicate : interpretedname\n\t\t\n\t\ttermseq : interpretedname\n\t\t\t\t| interpretedname termseq\n\t\t\n\t\tatomsent : OPEN predicate termseq CLOSE\n\t\t\n\t\tboolsent : OPEN andOr starter CLOSE \n\t\t\t\t| OPEN ifIff sentence sentence CLOSE \n\t\t\t\t| OPEN NOT sentence CLOSE \n\t\t\n\t\tandOr : AND \n\t\t\t\t| OR\n\t\t\n\t\tifIff : IF\n\t\t\t\t| IFF\n\t\t'
    
_lr_action_items = {'OPEN':([0,2,3,4,8,9,10,12,13,14,15,21,23,25,27,28,],[5,5,-5,-6,5,5,5,-14,-15,-16,-17,5,-10,-11,-13,-12,]),'$end':([1,2,3,4,6,23,25,27,28,],[0,-1,-5,-6,-2,-10,-11,-13,-12,]),'CLOSE':([2,3,4,6,16,17,18,19,20,22,23,24,25,26,27,28,],[-1,-5,-6,-2,-3,-4,23,-8,25,27,-10,-9,-11,28,-13,-12,]),'NOT':([5,],[10,]),'AND':([5,],[12,]),'OR':([5,],[13,]),'IF':([5,],[14,]),'IFF':([5,],[15,]),'NUMERAL':([5,7,11,16,17,19,],[16,16,-7,-3,-4,16,]),'QUOTEDSTRING':([5,7,11,16,17,19,],[17,17,-7,-3,-4,17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'starter':([0,2,8,],[1,6,20,]),'sentence':([0,2,8,9,10,21,],[2,2,2,21,22,26,]),'atomsent':([0,2,8,9,10,21,],[3,3,3,3,3,3,]),'boolsent':([0,2,8,9,10,21,],[4,4,4,4,4,4,]),'predicate':([5,],[7,]),'andOr':([5,],[8,]),'ifIff':([5,],[9,]),'interpretedname':([5,7,19,],[11,19,19,]),'termseq':([7,19,],[18,24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> starter","S'",1,None,None,None),
  ('starter -> sentence','starter',1,'p_starter','a3-parser-provided.py',97),
  ('starter -> sentence starter','starter',2,'p_starter','a3-parser-provided.py',98),
  ('interpretedname -> NUMERAL','interpretedname',1,'p_interpretedname','a3-parser-provided.py',105),
  ('interpretedname -> QUOTEDSTRING','interpretedname',1,'p_interpretedname','a3-parser-provided.py',106),
  ('sentence -> atomsent','sentence',1,'p_sentence','a3-parser-provided.py',111),
  ('sentence -> boolsent','sentence',1,'p_sentence','a3-parser-provided.py',112),
  ('predicate -> interpretedname','predicate',1,'p_predicate','a3-parser-provided.py',125),
  ('termseq -> interpretedname','termseq',1,'p_termseq','a3-parser-provided.py',130),
  ('termseq -> interpretedname termseq','termseq',2,'p_termseq','a3-parser-provided.py',131),
  ('atomsent -> OPEN predicate termseq CLOSE','atomsent',4,'p_atomsent','a3-parser-provided.py',139),
  ('boolsent -> OPEN andOr starter CLOSE','boolsent',4,'p_boolsent','a3-parser-provided.py',144),
  ('boolsent -> OPEN ifIff sentence sentence CLOSE','boolsent',5,'p_boolsent','a3-parser-provided.py',145),
  ('boolsent -> OPEN NOT sentence CLOSE','boolsent',4,'p_boolsent','a3-parser-provided.py',146),
  ('andOr -> AND','andOr',1,'p_andOr','a3-parser-provided.py',151),
  ('andOr -> OR','andOr',1,'p_andOr','a3-parser-provided.py',152),
  ('ifIff -> IF','ifIff',1,'p_ifIff','a3-parser-provided.py',157),
  ('ifIff -> IFF','ifIff',1,'p_ifIff','a3-parser-provided.py',158),
]
